CREATE DATABASE reminders_app;
-- \c reminders_app

CREATE TABLE REMINDER_OPTIONS(
REMINDER_OPTIONS_ID SERIAL PRIMARY KEY,
FREQUENCY INT, 
DATE_DUE DATE,
R_PRIORITY INT 
);

CREATE TABLE REMINDERS(
REMINDERS_ID SERIAL PRIMARY KEY,
R_NAME VARCHAR(20) NOT NULL,
R_DESCRIPTION VARCHAR (100) NOT NULL,
REMINDER_OPTION_ID INT REFERENCES REMINDER_OPTIONS(REMINDER_OPTIONS_ID)
);

CREATE TABLE MODE(
MODE_ID SERIAL PRIMARY KEY,
MODE_NAME VARCHAR(20) NOT NULL,
REMINDERS_ID INT REFERENCES REMINDERS(REMINDERS_ID)
);

CREATE TABLE SETTINGS(
SETTING_ID SERIAL PRIMARY KEY,
COLOUR_OPTION VARCHAR(10),
FREQUENCY INT,
R_OPTIONS_ID INT REFERENCES REMINDER_OPTIONS(REMINDER_OPTIONS_ID),
REMINDERS_ID INT REFERENCES REMINDERS(REMINDERS_ID),
MODE_ID INT REFERENCES MODE(MODE_ID)
);






