// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnqqq9LPtQWjvGz0-_2j3zCQclPbJ4Z0Y',
    appId: '1:910338667484:web:0d06823aadc0aa502dd519',
    messagingSenderId: '910338667484',
    projectId: 'reminderappdatabase-e5e8a',
    authDomain: 'reminderappdatabase-e5e8a.firebaseapp.com',
    storageBucket: 'reminderappdatabase-e5e8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCecMx2pKXlw9Sswg6ZM4NrwhXPtaMo6TI',
    appId: '1:910338667484:android:90b7e3af516a854c2dd519',
    messagingSenderId: '910338667484',
    projectId: 'reminderappdatabase-e5e8a',
    storageBucket: 'reminderappdatabase-e5e8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSz4UXBUSlIqJoWEZLH8Nw368WaEe2E-k',
    appId: '1:910338667484:ios:b5b991eb7bee6b4f2dd519',
    messagingSenderId: '910338667484',
    projectId: 'reminderappdatabase-e5e8a',
    storageBucket: 'reminderappdatabase-e5e8a.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSz4UXBUSlIqJoWEZLH8Nw368WaEe2E-k',
    appId: '1:910338667484:ios:336b905cc5b7e9d42dd519',
    messagingSenderId: '910338667484',
    projectId: 'reminderappdatabase-e5e8a',
    storageBucket: 'reminderappdatabase-e5e8a.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
